# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61422e7c135aab1de9543fb642b13737203903ab1550ab74b88992a3136121ed0fe939e164b53ecc7fdb31f359413b02a720ad954d490c77d79a3ac72d206c5

test:
  secret_key_base: 1f0f0201797907850dbbfd73188047c44976a1c3837c3092ab15a8840f2dbe7e9d88617855cf4c84b61ab54ec7198f19b687b732114496f554ab501b481535ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
